### ISSUE TITLE
Errors when running marmitek-gw/gateway.py

### ISSUE THREAD

**Issue by LaureCremieux** [pawmint/marmitek-gw#4]
Hi Romain,

Here are the errors I get when I run marmitek-gw/gateway.py. I don't get where they come from.
I made sure the mochad reader runs properly (btw I had to add  ``` # -*-coding:Latin-1 -* ``` at the top in order to make it work)

```
❯ python marmitek/gateway.py                                                                                                      [6:09:32 PM]
Traceback (most recent call last):
  File "marmitek/gateway.py", line 48, in <module>
    main()
  File "marmitek/gateway.py", line 11, in main
    default_file= '/home/laure/IPALdepo/marmitek-gw/resources/conf.json.default')
  File "build/bdist.linux-x86_64/egg/ubigate/gate.py", line 35, in __init__
  File "build/bdist.linux-x86_64/egg/ubigate/utils/config.py", line 84, in init
  File "build/bdist.linux-x86_64/egg/ubigate/utils/config.py", line 24, in _get_config
  File "build/bdist.linux-x86_64/egg/ubigate/utils/config.py", line 33, in _create_initial_config
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 936, in resource_filename
    self, resource_name
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1568, in get_resource_filename
    return self._extract_resource(manager, zip_path)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1587, in _extract_resource
    timestamp, size = self._get_date_and_size(self.zipinfo[zip_path])
KeyError: 'home/laure/IPALdepo/marmitek-gw/resources/conf.json.default'
```

The problem seems to come from conf.json.default, but I can't point the problem. Any idea? Thanks!

**Comment by RomainEndelin** [comment]
First answer:
It's always better to add ` # -*- coding: utf-8 -*-` rather than `Latin-1`.

For the other bug, it's more of a Ubigate problem. It comes from `pkg_resources`, to deal with external files and python packaging. It's always a mess, and brings lots of unexpected platform-dependant bugs...
Just in case, can you confirm that you have the file `/home/laure/IPALdepo/marmitek-gw/resources/conf.json.default` ? Also, I'd need more details : how do you run it ? do you use virtualenv ? Did you `python setup.py install` or `develop` ?

Your problem is in line 33 of ubigate/utils/config.py, in the call of `resource_filename(Requirement.parse(pkg_name), default_file)`. Can you make a `print(Requirement.parse(pkg_name)` just above ? From that point, run a python/ipython interpreter, and try out stuffs like:
```python
import pkg_resources

pkg_resources.resource_filename('<my_hardcoded_path>')
```

**Comment by LaureCremieux** [comment]
I confirm that I have the /home/laure/IPALdepo/marmitek-gw/resources/conf.json.default file
I did a python setup.py install, is that alright?
And ok I'll try what you mention tomorrow :) thanks a lot!

**Comment by RomainEndelin** [comment]
Yep, the `python setup.py install` is alright, as well as `python setup.py develop`. The difference is that they will have a different way to do the packaging (which is why sometimes "pkg_resources" works with one, but not with the other). Similarly, it may save it in a different place depending on whether you use a virtualenv or not.

Try to execute with `python setup.py develop` this time, to see whether it works.

**Comment by LaureCremieux** [comment]
Hi Romain, so:

* I'm not using Virtual env because I'm running everything on my computer, not on the Raspberry yet (although I tried with the Raspberry and got the exact same thing)

* I placed the ```print(Requirement.parse(pkg_name)``` as follows:
```
def _create_initial_config(user_dir, pkg_name, default_file):
    try:
        os.makedirs(user_dir) 
    except OSError:
    	print(Requirement.parse(pkg_name)
        pass
    shutil.copy(pkg_resources.resource_filename(Requirement.parse(pkg_name), 
                                                default_file), 
                os.path.join(user_dir, FILENAME)) 
    return _read_config(os.path.join(user_dir, FILENAME))
```

*  I ran ``` import pkg_resources ``` on the python interpreter, nothing happened

* Finally I used the develop instead of install, and got pretty much the same amount of errors:

```
 ❯ python gateway.py                                                                                                               [1:03:55 AM]
Traceback (most recent call last):
  File "gateway.py", line 48, in <module>
    main()
  File "gateway.py", line 11, in main
    default_file= 'resources/conf.json.default')
  File "build/bdist.linux-x86_64/egg/ubigate/gate.py", line 35, in __init__
  File "build/bdist.linux-x86_64/egg/ubigate/utils/config.py", line 84, in init
  File "build/bdist.linux-x86_64/egg/ubigate/utils/config.py", line 20, in _get_config
  File "build/bdist.linux-x86_64/egg/ubigate/utils/config.py", line 42, in _read_config
  File "/usr/lib/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting property name: line 9 column 5 (char 160)
```

:)

**Comment by RomainEndelin** [comment]
Thanks Laure :). Can you tell me what the print displays with `python setup.py install` ?

Also, about the interpreter, that `import` was actually a startpoint for you to test out ;).

It looks like the `python setup.py develop` actually raises another bug, that's weird... I'll try to look at these lines later on.

Also, please use virtualenv anyway, it's much cleaner for your system, and it may prevent some annoying issues when you work on several projects in parallel (like if your marmitek-gw and your ubigate testing are in different versions).

Last thing, I see you run `python gateway.py`, there is actually an executable `marmitek-gw`, defined in line 26 of `setup.py`.

Cheers

**Comment by LaureCremieux** [comment]
Hi Romain!

So now, whether I place the ```print(Requirement.parse(pkg_name)``` in the config.py or not, and whether I do the install or the developp, this is what I get:

```
laure@Robert ⮀ ~/IPALdepo/marmitek-gw/marmitek ⮀ ⭠ master ? ⮀
 ❯ marmitek-gw                                                                                                                     [6:26:50 PM]
Traceback (most recent call last):
  File "/usr/local/bin/marmitek-gw", line 9, in <module>
    load_entry_point('Marmitek-Gw==1.2.2', 'console_scripts', 'marmitek-gw')()
  File "/home/laure/IPALdepo/marmitek-gw/marmitek/gateway.py", line 11, in main
    default_file= 'resources/conf.json.default')
  File "build/bdist.linux-x86_64/egg/ubigate/gate.py", line 35, in __init__
  File "build/bdist.linux-x86_64/egg/ubigate/utils/config.py", line 84, in init
  File "build/bdist.linux-x86_64/egg/ubigate/utils/config.py", line 20, in _get_config
  File "build/bdist.linux-x86_64/egg/ubigate/utils/config.py", line 42, in _read_config
  File "/usr/lib/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting property name: line 9 column 5 (char 160)
```

I installed virtualenv, and have few questions about it:

- about the use of local environments: for example when I do ```workon virtualenvmarmitek```, I activate the virtual environment I've created there. So if my virtualenvmarmitek has been configured to run with Python2.1, my ```marmitek-gw``` will be read in Python2.1 (even if it's not the version installed on my computer). Am I right?

- should I install virtualenv on the Raspberry as well and transfer my virtualenvmarmitek from my computer to the raspberry?

- what is the initial configuration of a virtual environment when I create it? Is it my computer's environment?

Thank you!

**Comment by LaureCremieux** [comment]
Helloooo!

I think I found the bug: in both marmitek-gw/resources/conf.json.default and UbiGATE/resources/config/conf-gw.json.default, there's a syntaxic error in the JSON code:

In the "gateways" block, after "password": "<PWD>", there should be no coma (","). To see this you can test the JSON code in this verifier: http://jsonlint.com/

Since this fails, the config.py initialisation fails as well: 
because of these lines in _get_config, the JSON error is transfered permanently to the config file located in ```~/.config/marmitek-gw```.

```
dirs = AppDirs(name, author)
    for dir_conf in [dirs.user_config_dir, dirs.site_config_dir]:
        try:
            config = _read_config(os.path.join(dir_conf, FILENAME))
```

So I went there and removed the coma, and now it works.

**Comment by LaureCremieux** [comment]
Oh and also I added the encoder ```# -*- coding: utf-8 -*-``` at the top of every python file otherwise it doesn't work

**Comment by RomainEndelin** [comment]
Okay, I'm glad you fixed it. The config.py file is really dirty anyway, and we should clean it up some day. But as long as it does its job that can wait.

For the `# -*- coding: utf-8 -*-` I'm a bit surprised that it's necessary at every files, but it's a good practice anyway, so that's allright.

To answer your questions about virtualenv:

* You're right, you can use for instance python3.4 as default system-wide, if you run `mkvirtualenv <my_virtualenv> -p /usr/bin/python2, your virtualenv will be on python2. You can check that by testing some `python --version` inside and outside of your virtualenvs. If you want to easily install more versions of python on your machine (for instance the same version as what's on the Raspberry), check out pyenv (https://github.com/yyuu/pyenv).

* When you create a virtualenv, it's empty (you can test it with `pip freeze`). It only includes a raw python. Later on when you `pip install` stuffs or run `python setup.py develop/install`, try again the `pip freeze` to see the difference.

* No, we don't use virtualenv on the raspberry. We could, but it would be a bit more complicated than on your dev machine (we'd probably have to skip virtualenvwrapper), for very little benefits anyway. The installation of ubigate/marmitek/... is system-wide on the raspberry.
Moreover, rather than copy-pasting a virtualenv from your machine, it is better to make use of the git repository and the `setup.py` file, so that the install is declarative and fully reproducible.

I hope that's clear :).

Cheers'
